### ISSUE TITLE
`ucc` builds did not pick up latest `ucx` (v1.16.0).

### ISSUE THREAD

**Issue by leofang** [conda-forge/ucc-feedstock#7]
The assumption in #2 is that we use v1.16.0 build 2 or above. This is currently broken.

**Comment by leofang** [comment]
@conda-forge-admin, please rerender

**Comment by leofang** [comment]
The root cause is we still pin at v1.15.0 globally:
https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/604816c8db83f9ceefbc4a04ba4de09747cf3822/recipe/conda_build_config.yaml#L857-L858
and it seems the migration bot failed to issue a version update PR to update the pinning (cc: @conda-forge/ucx-split for vis)

**Comment by jakirkham** [comment]
Please see upstream issue: https://github.com/regro/cf-scripts/issues/2519

**Comment by jakirkham** [comment]
If it is ok, I would like to use this feedstock as a test case to confirm we have fixed this issue (once we do have it fully fixed)

**Comment by leofang** [comment]
by all means, thx

**Comment by jakirkham** [comment]
Bot migrator is in thanks to help from Matt! 🙏

So we should see a migration PR here shortly

xref: https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/5836

**Comment by leofang** [comment]
@jakirkham it works now! #10 

But it was delayed quite a bit -- I see the migrator was already issued to `openmpi` (https://github.com/conda-forge/openmpi-feedstock/pull/154) 20 hours ago but not here. I think what happened was that the dependency version migration only works when the feedstock is on the latest version, which was not the case. I had to merge #9 first, and within an hour #10 arrived.

**Comment by leofang** [comment]
Both UCC versions are rebuilt with against UCX 1.16:
- #10 
- #8 (manual backport to a separate branch)

**Comment by jakirkham** [comment]
> @jakirkham it works now! #10
> 
> But it was delayed quite a bit -- I see the migrator was already issued to `openmpi` ([conda-forge/openmpi-feedstock#154](https://github.com/conda-forge/openmpi-feedstock/pull/154)) 20 hours ago but not here. I think what happened was that the dependency version migration only works when the feedstock is on the latest version, which was not the case. I had to merge #9 first, and within an hour #10 arrived.

Glad to hear that

Feel free to [raise an issue with more details]( https://github.com/regro/cf-scripts/issues/new ) if you like

Though it's worth remembering that the bot runs on an infrequently run cron job. Plus we recently added a NumPy 2 migrator to its load (though have recently paused that to work out some kinks)

Personally want to see how things go in future migrations
